### DISCUSSION TITLE
up-active feedback for form with 2 buttons

### DISCUSSION THREAD

**Discussion by spapas** [unpoly/unpoly#470] [Q&A] [answered]
Hello, I've got a form that has two buttons (a submit and a cancel one) like this:

```html
<form>
<!-- inputs -->
<button id='submitButton' type='submit' class='btn btn-{{ action.get_color_str|lower }}' >
  {{ action.get_button_title }}
  <span class="my-indicator  spinner-border spinner-border-sm "
    role="status"></span>
</button>

<a up-follow href='{% url "app_detail" app.id %}' class='btn btn-secondary' >
  Cancel
  <span class="my-indicator  spinner-border spinner-border-sm "
      role="status"></span>
</a>
</form>
```

Notice that both have a `my-indicator` element that would render a spinner. This element is styled like this:

```css
.my-indicator{
    display:none;
}

.up-active .my-indicator{
    display:inline-block;
}
```

The problem with this approach is that when I press either the submit or the cancel button it will render *both* indicators! This confuses the users. 

Can you recommend me a way to display the indicator only on he button that was pressed? Please consider that there are cases where a form may have multiple submit buttons (each one passing a value) so rendering the Cancel link outisde the form isn't a good solution.

**Comment by triskweline** [comment, marked as answer]
Unpoly 3 will assign the `.up-active` class to the submit button used, not to the form.

As a workaround, maybe you can rearrange your styles like this:

```css
.my-indicator {
    display:none;
}

a.up-active,
form.up-active button:focus {
    display:inline-block;
}
```

**Comment by spapas** [comment]
@triskweline thank you very much for the quick answer! 

I rearranged my styles like:

```css
    a.up-active .my-indicator, form.up-active button:focus .my-indicator {
        display:inline-block;
    }
```

and it works now! (the `.my-indicator` is inside the `button` or `a` elements)
